### ISSUE TITLE
Incorrect install_requires in setup.py

### ISSUE THREAD

**Issue by peterkuma** [apalarcon/CyTRACK#1]
`install_requires` in `setup.py` contains names of built-in Python modules which should not be there. This option is for specifying external Python packages available through PyPI, which `pip install` installs automatically when executing `setup.py`. The following should be omitted:

- `time`
- `datetime`
- `functools`
- `imp`
- `sys`
- `os`
- `fnmatch`
- `math`
- `argparse`

The correct value of the option should be:

`install_requires=["numpy","mpi4py","netCDF4","scipy","matplotlib","xarray","scikit-learn"]`

**Comment by apalarcon** [comment]
Thank you very much for your feedback.

**Comment by peterkuma** [comment]
Sorry I have just noticed that also "cdsapi" and "cartopy" are missing among the required packages.

**Comment by apalarcon** [comment]
"cdsapi" and "cartopy" are not required packages for a basic CyTRACK run. Note in the README file that users can check if these packages are installed to use those features of CyTRACK.
