### ISSUE TITLE
Zero cyclones found on a given day for a whole hemisphere

### ISSUE THREAD

**Issue by peterkuma** [apalarcon/CyTRACK#3]
Hi,

I have tried using CyTRACK for finding cyclones in the Southern Hemisphere during one day on 2020-01-01 in ERA5 data. The ERA5 data were downloaded successfully, but I get a message `CyTRACK found 0 ECs`. I haven't changed any of the default parameters in the template other than setting the cyclone type ("EC"), source ("ERA5"), output and tmp paths, era_file_prefix ("era5"), search_region ("SH"), search_limits (None, but I also tried [0,-90,360,-40]), checking_upper_levels_parameters ("no"), begin_* (2020-01-01 00) and end_* (2020-01-02 00) and  calendar ("366d").

Do you know what might be the problem? The full cfg file and console output are attached. One data file is produced (`CyTRACK_SH_2020010100-2020010200_ERA5_EC.dat`), with no content. A few tmp files are produced for every time step with about 4 kB of numbers each (attached).

The version of CyTRACK used is the release 1.0.1 from 27 March 2024, but it is the same with the latest code from GitHub (2b8c1f9).

Attachment: [cytrack.zip](https://github.com/apalarcon/CyTRACK/files/15392681/cytrack.zip)

Thank you!

**Comment by peterkuma** [comment]
I have now figured out that if the time period of the analysis is longer, ECs are found. But it is not quite clear to me how long the minimum time interval should be.

**Comment by apalarcon** [comment]
Note that you configured CyTRACK to run for 24 hours, but you declared "dt_lifetime=48" in the configuration file. Therefore, all tracks shorter than 48 hours are removed.

**Comment by peterkuma** [comment]
Thank you. I thought it might be taking the previous days into consideration automatically, since it has downloaded ERA5 for weeks before the declared begin_* time.
